FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests


FROM bellsoft/liberica-openjdk-debian:21

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8086

CMD ["java", "-jar", "app.jar"]
